Repository projectsyn/component-loki, pull requests merged in 2024-09, with the labels that each got.

#1 Use "namespaced" RBAC mode by default
  class/defaults.yml
  component/main.jsonnet
  tests/defaults.yml
  tests/golden/defaults/loki/loki/10_helm_loki/loki/templates/backend/clusterrole.yaml
  tests/golden/defaults/loki/loki/10_helm_loki/loki/templates/backend/clusterrolebinding.yaml
Labels: enhancement

#2 Expand environment variables in config by default
  class/defaults.yml
  tests/golden/defaults/loki/loki/10_helm_loki/loki/templates/backend/statefulset-backend.yaml
  tests/golden/defaults/loki/loki/10_helm_loki/loki/templates/read/deployment-read.yaml
  tests/golden/defaults/loki/loki/10_helm_loki/loki/templates/write/statefulset-write.yaml
Labels: bug

#3 Add parameter documentation
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/loki/loki/10_helm_loki/loki/templates/backend/statefulset-backend.yaml
  tests/golden/defaults/loki/loki/10_helm_loki/loki/templates/read/deployment-read.yaml
Labels: documentation
